#########################################################################
# Title:         GDFLN: Cloudflare                                      #
# Author(s):     desimaniac, l3udd                                      #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Install 'dnsutils'
  apt: "name=dnsutils state=present"
  become: yes

- name: Get Public IP Address
  shell: dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com | awk -F'\"' '{ print $2}'
  register: public_ip_lookup

- name: Set 'public_ip' variable
  set_fact:
    public_ip: "{{ public_ip_lookup.stdout }}"

- name: Set 'record' variable
  set_fact:
    record: "{{ subdomain }}.{{ basics.domain }}"

- name: Set DNS Record
  cloudflare_dns:
    account_api_token: "{{ cloudflare.api }}"
    account_email: "{{ cloudflare.email }}"
    zone: "{{ basics.domain }}"
    state: present
    solo: true
    proxied: no
    type: A
    value: "{{ public_ip }}"
    record: "{{ subdomain }}"

- name: Display DNS Record
  debug:
    msg: "DNS Record for '{{ record }}' set to '{{ public_ip }}'."
